// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf7V7fXSarxnXThr_FE9eu2WIwUn0ROFU',
    appId: '1:754689124467:web:27956b180955477a3ca206',
    messagingSenderId: '754689124467',
    projectId: 'notes-app-attax442',
    authDomain: 'notes-app-attax442.firebaseapp.com',
    storageBucket: 'notes-app-attax442.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4HCxCoJkD1rA1Ikt6qYwpggN0JrJ6jA',
    appId: '1:754689124467:android:4c4fa0d0f6aec05e3ca206',
    messagingSenderId: '754689124467',
    projectId: 'notes-app-attax442',
    storageBucket: 'notes-app-attax442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLKXItHC10w-Haeh2OfgeMm_9uC_SbsrY',
    appId: '1:754689124467:ios:7b4c53b7326214f63ca206',
    messagingSenderId: '754689124467',
    projectId: 'notes-app-attax442',
    storageBucket: 'notes-app-attax442.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLKXItHC10w-Haeh2OfgeMm_9uC_SbsrY',
    appId: '1:754689124467:ios:7b4c53b7326214f63ca206',
    messagingSenderId: '754689124467',
    projectId: 'notes-app-attax442',
    storageBucket: 'notes-app-attax442.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf7V7fXSarxnXThr_FE9eu2WIwUn0ROFU',
    appId: '1:754689124467:web:cd158de31dc7810d3ca206',
    messagingSenderId: '754689124467',
    projectId: 'notes-app-attax442',
    authDomain: 'notes-app-attax442.firebaseapp.com',
    storageBucket: 'notes-app-attax442.firebasestorage.app',
  );
}
